INSERT INTO student (name, groupnumber, birthday, id) values ('John', 1, CURRENT_DATE, 1);
INSERT INTO student (name, groupnumber, birthday) values ('Chris', 1, CURRENT_DATE);
INSERT INTO student (name, groupnumber, birthday) values ('Carl', 1, CURRENT_DATE);
INSERT INTO student (name, groupnumber, birthday) values ('Oliver', 2, CURRENT_DATE);
INSERT INTO student (name, groupnumber, birthday) values ('James', 2, CURRENT_DATE);
INSERT INTO student (name, groupnumber, birthday) values ('Lucas', 2, CURRENT_DATE);
INSERT INTO student (name, groupnumber, birthday) values ('Henry', 2, CURRENT_DATE);
INSERT INTO student (name, groupnumber, birthday) values ('Jacob', 3, CURRENT_DATE);
INSERT INTO student (name, groupnumber, birthday) values ('Logan', 3, CURRENT_DATE);
INSERT INTO student (name, groupnumber, birthday) values ('New', 4, CURRENT_DATE);
INSERT INTO student (name, groupnumber, birthday) values ('Kid', 4, CURRENT_DATE);
INSERT INTO student (name, groupnumber, birthday) values ('Block', 5, CURRENT_DATE);
INSERT INTO student (name, groupnumber, birthday) values ('Game', 5, CURRENT_DATE);
INSERT INTO subject (name, grade, description, id) values ('Art', 1, 'EMPTY', 1);
INSERT INTO subject (name, grade, description) values ('Music', 1, 'EMPTY');
INSERT INTO subject (name, grade, description) values ('Geography', 2, 'EMPTY');
INSERT INTO subject (name, grade, description) values ('History', 2, 'EMPTY');
INSERT INTO subject (name, grade, description) values ('PE', 3, 'EMPTY');
INSERT INTO subject (name, grade, description) values ('Math', 3, 'EMPTY');
INSERT INTO subject (name, grade, description) values ('Science', 4, 'EMPTY');
INSERT INTO subject (name, grade, description) values ('IT', 4, 'EMPTY');
INSERT INTO subject (name, grade, description) values ('Geometry', 5, 'EMPTY');
INSERT INTO subject (name, grade, description) values ('Theater', 5, 'EMPTY');
INSERT INTO paymenttype (name, id) values ('DAILY', 1);
INSERT INTO paymenttype (name, id) values ('WEEKLY', 2);
INSERT INTO paymenttype (name, id) values ('MONTHLY', 3);
INSERT INTO payment (type_id, student_id, amount, payment_date, id) values (2, 1, 1, CURRENT_TIMESTAMP, 1);
INSERT INTO payment (type_id, student_id, amount, payment_date) values (3, 4, 1, CURRENT_TIMESTAMP);
INSERT INTO payment (type_id, student_id, amount, payment_date) values (2, 7, 1, CURRENT_TIMESTAMP);
INSERT INTO payment (type_id, student_id, amount, payment_date) values (1, 5, 1, CURRENT_TIMESTAMP);
INSERT INTO payment (type_id, student_id, amount, payment_date) values (1, 6, 1, CURRENT_TIMESTAMP);
INSERT INTO payment (type_id, student_id, amount, payment_date) values (2, 10, 1, CURRENT_TIMESTAMP);
INSERT INTO payment (type_id, student_id, amount, payment_date) values (3, 2, 1, CURRENT_TIMESTAMP);
INSERT INTO mark (mark, student_id, subject_id) values (8, 2, 1);
INSERT INTO mark (mark, student_id, subject_id) values (5, 4, 4);
INSERT INTO mark (mark, student_id, subject_id) values (9, 5, 3);
INSERT INTO mark (mark, student_id, subject_id) values (4, 8, 6);
INSERT INTO mark (mark, student_id, subject_id) values (9, 9, 5);
INSERT INTO mark (mark, student_id, subject_id) values (3, 3, 3);
INSERT INTO mark (mark, student_id, subject_id) values (6, 5, 2);
INSERT INTO mark (mark, student_id, subject_id) values (7, 1, 5);