INSERT INTO student (name, groupnumber, birthday) values ('John', 1, '1974-03-09');
INSERT INTO student (name, groupnumber, birthday) values ('Chris', 1, '1974-03-09');
INSERT INTO student (name, groupnumber, birthday) values ('Carl', 1, '1974-03-09');
INSERT INTO student (name, groupnumber, birthday) values ('Oliver', 2, '1974-03-09');
INSERT INTO student (name, groupnumber, birthday) values ('James', 2, '1974-03-09');
INSERT INTO student (name, groupnumber, birthday) values ('Lucas', 2, '1974-03-09');
INSERT INTO student (name, groupnumber, birthday) values ('Henry', 2, '1974-03-09');
INSERT INTO student (name, groupnumber, birthday) values ('Jacob', 3, '1974-03-09');
INSERT INTO student (name, groupnumber, birthday) values ('Logan', 3, '1974-03-09');
INSERT INTO student (name, groupnumber, birthday) values ('New', 4, '1974-03-09');
INSERT INTO student (name, groupnumber, birthday) values ('Kid', 4, '1974-03-09');
INSERT INTO student (name, groupnumber, birthday) values ('Block', 5, '1974-03-09');
INSERT INTO student (name, groupnumber, birthday) values ('Game', 5, '1974-03-09');
INSERT INTO subject (name, grade, description, id) values ('Art', 1, 'EMPTY', 1);
INSERT INTO subject (name, grade, description) values ('Music', 1, 'EMPTY');
INSERT INTO subject (name, grade, description) values ('Geography', 2, 'EMPTY');
INSERT INTO subject (name, grade, description) values ('History', 2, 'EMPTY');
INSERT INTO subject (name, grade, description) values ('PE', 3, 'EMPTY');
INSERT INTO subject (name, grade, description) values ('Math', 3, 'EMPTY');
INSERT INTO subject (name, grade, description) values ('Science', 4, 'EMPTY');
INSERT INTO subject (name, grade, description) values ('IT', 4, 'EMPTY');
INSERT INTO subject (name, grade, description) values ('Geo', 5, 'EMPTY');
INSERT INTO subject (name, grade, description) values ('The', 5, 'EMPTY');
insert into paymenttype ( name) values ('DAILY');
insert into paymenttype ( name) values ('WEEKLY');
insert into paymenttype ( name) values ('MONTHLY');
INSERT INTO payment (type_id, student_id, amount, payment_date) values (SELECT id FROM paymenttype WHERE name = 'WEEKLY', SELECT id FROM student WHERE name = 'John', 301.19, '2020-07-02 17:45:36');
INSERT INTO payment (type_id, student_id, amount, payment_date) values (SELECT id FROM paymenttype WHERE name = 'MONTHLY', SELECT id FROM student WHERE name = 'Oliver', 301.19, '2020-07-02 17:45:36');
INSERT INTO payment (type_id, student_id, amount, payment_date) values (SELECT id FROM paymenttype WHERE name = 'WEEKLY', SELECT id FROM student WHERE name = 'Henry', 301.19, '2020-07-02 17:45:36');
INSERT INTO payment (type_id, student_id, amount, payment_date) values (SELECT id FROM paymenttype WHERE name = 'DAILY', SELECT id FROM student WHERE name = 'James', 301.19, '2020-07-02 17:45:36');
INSERT INTO payment (type_id, student_id, amount, payment_date) values (1, 6, 301.19, '2020-07-02 17:45:36');
INSERT INTO payment (type_id, student_id, amount, payment_date) values (2, 10, 301.19, '2020-07-02 17:45:36');
INSERT INTO payment (type_id, student_id, amount, payment_date) values (3, 2, 301.19, '2020-07-02 17:45:36');
INSERT INTO mark (mark, student_id, subject_id) values (8, 2, 1);
INSERT INTO mark (mark, student_id, subject_id) values (5, 4, 4);
INSERT INTO mark (mark, student_id, subject_id) values (9, 5, 3);
INSERT INTO mark (mark, student_id, subject_id) values (4, 8, 6);
INSERT INTO mark (mark, student_id, subject_id) values (9, 9, 5);
INSERT INTO mark (mark, student_id, subject_id) values (3, 3, 3);
INSERT INTO mark (mark, student_id, subject_id) values (6, 5, 2);
INSERT INTO mark (mark, student_id, subject_id) values (7, 1, 5);